/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#683364",
        "on-surface-variant": "#7a6a78",
        "tertiary-fixed": "#e4e4cc",
        "on-secondary-fixed": "#241a00",
        "surface-bright": "#fffdf7",
        "primary": "#4b284d",
        "surface-tint": "#f5b1ea",
        "surface-container-highest": "#e8e4e6",
        "on-secondary-container": "#342800",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#D4AF37",
        "on-tertiary-container": "#81826d",
        "inverse-on-surface": "#fffdf7",
        "tertiary-container": "#161809",
        "surface": "#fffdf7",
        "on-tertiary-fixed-variant": "#474836",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c8c8b0",
        "on-primary-container": "#a96ca1",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#cfc8cc",
        "on-tertiary-fixed": "#1b1d0e",
        "surface-container-high": "#f5f0f3",
        "primary-container": "#300030",
        "surface-container-low": "#faf5f8",
        "on-error": "#ffffff",
        "on-primary-fixed": "#360435",
        "secondary-container": "#af8d11",
        "secondary-fixed": "#ffe088",
        "tertiary": "#c8c8b0",
        "on-background": "#4B284D",
        "background": "#fffdf7",
        "on-surface": "#4B284D",
        "on-tertiary": "#303221",
        "inverse-surface": "#4B284D",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#f5b1ea",
        "surface-container": "#f8f3f6",
        "outline": "#9b8d96",
        "secondary": "#D4AF37",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#574500",
        "surface-dim": "#ebe6e8",
        "inverse-primary": "#834a7d",
        "primary-fixed": "#ffd7f5",
        "surface-variant": "#f0eaed"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "display": ["Playfair Display", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "notoSerif": ["Noto Serif", "serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "1rem", "xl": "1.5rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
